apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pg-clusters
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: pg-cluster
    repoURL: 'https://github.com/luizzvinicius/gitops-cnpg.git'
    targetRevision: HEAD
  sources: []
  project: default